language: node_js
node_js:
  - node
dist: trusty
sudo: false
install: npm install -ddd
cache:
  directories:
    - node_modules
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
    - gh-pages
notifications:
  webhooks: http://webhook.hakatashi.com/travis
